# Generated by Django 5.0.3 on 2024-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0002_remove_sudoku_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='solution',
            field=models.CharField(default='[[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]', max_length=300),
        ),
        migrations.AddField(
            model_name='sudoku',
            name='start',
            field=models.CharField(default='[[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]', max_length=300),
        ),
    ]
