# Generated by Django 5.0.3 on 2024-05-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0004_usersudoku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersudoku',
            old_name='hintsCount',
            new_name='hints_count',
        ),
    ]
