# Generated by Django 5.0.3 on 2024-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0005_rename_hintscount_usersudoku_hints_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersudoku',
            name='progress',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
