# Generated by Django 5.0.3 on 2024-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0006_usersudoku_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
