# Generated by Django 5.0.3 on 2024-05-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0007_sudoku_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersudoku',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
