# Generated by Django 5.0.3 on 2024-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0008_alter_usersudoku_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='solution',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='start',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usersudoku',
            name='progress',
            field=models.JSONField(null=True),
        ),
    ]
