# Generated by Django 5.0.3 on 2024-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0009_alter_sudoku_solution_alter_sudoku_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersudoku',
            name='progress',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
