# Generated by Django 5.0.3 on 2024-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokus', '0011_alter_usersudoku_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersudoku',
            name='progress',
            field=models.JSONField(default=list),
        ),
    ]
